feature_extractor:
  pca_radius: 0.5                  # [meter], radius for terrain feature extraction
  grid_res: 0.1                    # [meter], resolution for local vacancy grid mapping (sparsity calculation)
